"""Generate deterministic repository references from implementation sources."""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "docs" / "generated"
HEADER = (
    "<!-- Generated by `python -m scripts.generate_docs`. Do not edit. -->\n\n"
)


def expression(node: ast.AST | None) -> str:
    if node is None:
        return ""
    return ast.unparse(node)


def setting_reference() -> str:
    tree = ast.parse((ROOT / "app" / "config.py").read_text(encoding="utf-8"))
    rows: list[tuple[str, str, str]] = []
    for node in tree.body:
        if not isinstance(node, ast.ClassDef) or node.name != "Settings":
            continue
        for item in node.body:
            if not isinstance(item, ast.AnnAssign) or not isinstance(
                item.target, ast.Name
            ):
                continue
            rows.append(
                (
                    item.target.id.upper(),
                    expression(item.annotation),
                    expression(item.value),
                )
            )

    lines = [
        HEADER,
        "# Configuration reference\n\n",
        "Source: `app/config.py::Settings`. Regenerate with "
        "`python -m scripts.generate_docs`.\n\n",
        "Secret values are intentionally not read or rendered. Production "
        "requirements are documented in `docs/sdlc/CONFIGURATION.md`.\n\n",
        "| Environment variable | Type | Code default |\n",
        "|---|---|---|\n",
    ]
    lines.extend(
        f"| `{name}` | `{kind}` | `{default}` |\n"
        for name, kind, default in rows
    )
    return "".join(lines)


@dataclass(frozen=True)
class Route:
    method: str
    path: str
    handler: str
    source: str


def routes_from(path: Path) -> list[Route]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    routes: list[Route] = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            if not isinstance(decorator, ast.Call) or not isinstance(
                decorator.func, ast.Attribute
            ):
                continue
            method = decorator.func.attr.upper()
            if method not in {"GET", "POST", "PUT", "PATCH", "DELETE"}:
                continue
            if not decorator.args or not isinstance(
                decorator.args[0], ast.Constant
            ):
                continue
            route_path = decorator.args[0].value
            if not isinstance(route_path, str):
                continue
            routes.append(
                Route(
                    method=method,
                    path=route_path,
                    handler=node.name,
                    source=path.relative_to(ROOT).as_posix(),
                )
            )
    return routes


def api_reference() -> str:
    source_files = [ROOT / "app" / "main.py", *sorted(
        (ROOT / "app" / "api" / "routers").glob("*.py")
    )]
    routes = sorted(
        (route for path in source_files for route in routes_from(path)),
        key=lambda route: (route.path, route.method),
    )
    lines = [
        HEADER,
        "# API route reference\n\n",
        "Source: FastAPI decorators in `app/main.py` and "
        "`app/api/routers/`. Regenerate with "
        "`python -m scripts.generate_docs`.\n\n",
        "Field-level request and response schemas remain authoritative in "
        "FastAPI OpenAPI and `app/api/schemas.py`.\n\n",
        "| Method | Path | Handler | Source |\n",
        "|---|---|---|---|\n",
    ]
    lines.extend(
        f"| `{route.method}` | `{route.path}` | `{route.handler}` | "
        f"`{route.source}` |\n"
        for route in routes
    )
    return "".join(lines)


def bool_keyword(call: ast.Call, name: str) -> bool:
    for keyword in call.keywords:
        if keyword.arg == name and isinstance(keyword.value, ast.Constant):
            return bool(keyword.value.value)
    return False


def keyword_value(call: ast.Call, name: str) -> str:
    for keyword in call.keywords:
        if keyword.arg == name:
            return expression(keyword.value)
    return ""


def foreign_key(call: ast.Call) -> str:
    for argument in call.args[2:]:
        if not isinstance(argument, ast.Call):
            continue
        function = argument.func
        if isinstance(function, ast.Name) and function.id == "ForeignKey":
            if argument.args and isinstance(argument.args[0], ast.Constant):
                return str(argument.args[0].value)
    return ""


def data_reference() -> str:
    tree = ast.parse((ROOT / "app" / "database.py").read_text(encoding="utf-8"))
    tables: list[tuple[str, list[tuple[str, str, str, str]]]] = []
    for node in tree.body:
        if not isinstance(node, ast.Assign) or not isinstance(node.value, ast.Call):
            continue
        function = node.value.func
        if not isinstance(function, ast.Name) or function.id != "Table":
            continue
        if not node.value.args or not isinstance(node.value.args[0], ast.Constant):
            continue
        name = str(node.value.args[0].value)
        columns: list[tuple[str, str, str, str]] = []
        for argument in node.value.args[2:]:
            if not isinstance(argument, ast.Call):
                continue
            column_function = argument.func
            if not isinstance(column_function, ast.Name) or column_function.id != "Column":
                continue
            if not argument.args or not isinstance(argument.args[0], ast.Constant):
                continue
            column_name = str(argument.args[0].value)
            column_type = expression(argument.args[1]) if len(argument.args) > 1 else ""
            flags = []
            if bool_keyword(argument, "primary_key"):
                flags.append("PK")
            if bool_keyword(argument, "unique"):
                flags.append("unique")
            nullable = keyword_value(argument, "nullable")
            if nullable == "False":
                flags.append("not null")
            columns.append(
                (column_name, column_type, ", ".join(flags), foreign_key(argument))
            )
        tables.append((name, columns))

    lines = [
        HEADER,
        "# Relational data dictionary\n\n",
        "Source: SQLAlchemy metadata in `app/database.py`. Regenerate with "
        "`python -m scripts.generate_docs`.\n\n",
        "Alembic revisions remain authoritative for production schema history.\n",
    ]
    for table, columns in tables:
        lines.extend(
            [
                f"\n## `{table}`\n\n",
                "| Column | Type | Constraints | Reference |\n",
                "|---|---|---|---|\n",
            ]
        )
        lines.extend(
            f"| `{name}` | `{kind}` | {flags} | "
            f"{f'`{reference}`' if reference else ''} |\n"
            for name, kind, flags, reference in columns
        )
    return "".join(lines)


def expected_outputs() -> dict[Path, str]:
    return {
        GENERATED / "api-routes.md": api_reference(),
        GENERATED / "configuration.md": setting_reference(),
        GENERATED / "data-dictionary.md": data_reference(),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when generated references are missing or stale.",
    )
    args = parser.parse_args()
    outputs = expected_outputs()
    if args.check:
        stale = [
            path.relative_to(ROOT).as_posix()
            for path, content in outputs.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            raise SystemExit(
                "Generated documentation is stale: "
                + ", ".join(stale)
                + ". Run `python -m scripts.generate_docs`."
            )
        print("Generated documentation is current.")
        return

    GENERATED.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(path.relative_to(ROOT))


if __name__ == "__main__":
    main()
