"""从文档清单生成 MkDocs Material 站点配置（``mkdocs.yml``）。

读取 ``docs/document-manifest.json`` 作为导航单一数据源，输出一份带中英双语
（``mkdocs-static-i18n``）的 MkDocs Material 配置。本脚本只生成配置与导航，
文档内容仍由 ``docs/`` 与 ``docs/zh-CN/`` 提供，与 ``make docs-generate`` 维护
的中文镜像保持单一事实来源。

用法::

    python -m scripts.generate_docs_site          # 生成 mkdocs.yml 并补建别名软链
    python -m scripts.generate_docs_site --check  # 校验 mkdocs.yml 是否最新

实现要点（已通过 ``mkdocs build --strict`` 验证）：

- 仓库根目录的 ``README.md``/``ARCHITECTURE.md`` 等 6 个入口文档位于 ``docs_dir``
  之外，mkDocs 无法渲染，按既定范围决策**不纳入站点导航**。
- ``docs/ux/`` 目录名恰好匹配 i18n 插件的两字母语言码正则（``^[a-z]{2}$``），会被
  误判为本地化目录从而被忽略。解决办法：用 ``exclude_docs`` 排除真实 ``ux/``，
  建一个非冲突的别名软链 ``docs/experience`` -> ``ux``，并在导航里改用
  ``experience/`` 路径。
- 文档里大量指向仓库根（``../ARCHITECTURE.md``）、``tests/``、``eval/``、
  ``.env.example`` 等站点外目标的相对链接是既有的仓库内引用，不在 ``docs_dir``
  解析范围内。通过 ``validation`` 把 ``not_found`` 设为 ``ignore`` 容忍它们，
  避免改写源文档（仓库文档是事实来源）。
- 中文 locale 用 ``zh-CN`` 以匹配 ``docs/zh-CN/`` 目录，但因 Material 主题缺少
  ``zh-CN`` 语言模板，在 locale 配置里把 ``theme.language`` 回退到 ``zh``。
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
MANIFEST_PATH = DOCS / "document-manifest.json"
MKDOCS_PATH = ROOT / "mkdocs.yml"

# 站点导航的章节顺序与人类可读标题。
GROUP_ORDER: list[tuple[str, str]] = [
    ("entrypoints", "Getting started"),
    ("product", "Product"),
    ("experience", "Experience"),
    ("architecture", "Architecture"),
    ("delivery", "Delivery"),
    ("quality", "Quality"),
    ("release", "Release"),
    ("operations", "Operations"),
    ("security", "Security"),
    ("governance", "Governance"),
    ("generated", "Generated references"),
]

# 位于 ``docs/`` 之外的根级入口文档，mkDocs 无法渲染，故不纳入导航。
ROOT_ENTRYPOINTS = {
    "AGENTS.md",
    "README.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "CHANGELOG.md",
    "ARCHITECTURE.md",
}

# 目录名与 i18n 两字母语言码冲突，必须改用别名软链。
# 键为真实目录，值为站点内使用的别名；别名软链在生成时建到 ``docs/`` 下。
DIR_ALIASES: dict[str, str] = {"ux": "experience"}

HEADER = (
    "# Generated by `python -m scripts.generate_docs_site`. Do not edit.\n"
    "# Regenerate after changing docs/document-manifest.json.\n"
)


def ensure_aliases() -> list[str]:
    """为冲突目录创建非冲突的别名软链，返回已处理的别名列表。

    软链相对 ``docs/`` 创建（``experience`` -> ``ux``），属于构建辅助物，
    应由本 target 重建而非手工维护。
    """
    created: list[str] = []
    for real, alias in DIR_ALIASES.items():
        link = DOCS / alias
        target = real  # 相对 docs/ 的目标
        if link.is_symlink():
            if os.readlink(link) != target:
                link.unlink()
                link.symlink_to(target, target_is_directory=True)
                created.append(alias)
        elif link.exists():
            # 占位实体阻碍建链，告警但不破坏：交给人工裁决。
            print(f"warning: {link} exists and is not a symlink; skip aliasing {real}")
        else:
            link.symlink_to(target, target_is_directory=True)
            created.append(alias)
    return created


def _title_from_path(rel: str) -> str:
    """从文件名推导人类可读的导航标题。

    优先取文档首个一级标题；缺失时退化为去扩展名、连字符转空格的文件名。
    """
    path = DOCS / rel
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        stem = Path(rel).stem
        return stem.replace("-", " ").replace("_", " ")
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            title = stripped[2:].strip()
            return title.split(" <!--", 1)[0].strip()
    stem = Path(rel).stem
    return stem.replace("-", " ").replace("_", " ")


def _apply_alias(rel: str) -> str:
    """把 docs 相对路径里的冲突目录首段替换为别名。"""
    parts = rel.split("/", 1)
    if len(parts) == 2 and parts[0] in DIR_ALIASES:
        return f"{DIR_ALIASES[parts[0]]}/{parts[1]}"
    return rel


def build_nav(manifest: dict[str, Any]) -> list[Any]:
    """把文档清单转换为 MkDocs 导航结构。

    每个生命周期分组成为一节；只有 ``docs/`` 下、磁盘上真实存在的文件才进入导航。
    冲突目录（``ux``）改用别名软链路径，避开 i18n 误判。
    """
    lifecycle = manifest["lifecycle"]
    nav: list[Any] = []
    for group_key, group_title in GROUP_ORDER:
        files = lifecycle.get(group_key, [])
        entries: list[dict[str, str]] = []
        for repo_relative in files:
            if repo_relative in ROOT_ENTRYPOINTS:
                continue
            if not repo_relative.startswith("docs/"):
                continue
            docs_relative = repo_relative[len("docs/") :]
            if not (DOCS / docs_relative).is_file():
                print(f"warning: {repo_relative} listed in manifest but missing on disk")
                continue
            entries.append(
                {_title_from_path(docs_relative): _apply_alias(docs_relative)}
            )
        if entries:
            nav.append({group_title: entries})
    return nav


def build_config() -> dict[str, Any]:
    """组装完整的 MkDocs Material + i18n 配置字典。"""
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    nav = build_nav(manifest)
    # exclude_docs 排除冲突真实目录（其内容由别名软链提供）。gitignore 风格，每条一行。
    exclude = "".join(f"{real}/\n" for real in DIR_ALIASES)
    return {
        "site_name": "Interview Agent",
        "site_description": (
            "Interview Agent 文档站：产品、架构、开发、验证、发布与运维的完整生命周期。"
        ),
        "site_url": "https://interview-agent.github.io/interview-agent/",
        "docs_dir": "docs",
        # 仓库链接让站点顶部出现 GitHub 入口；占位由部署方按实际仓库改写。
        "repo_url": "https://github.com/interview-agent/interview-agent",
        "repo_name": "interview-agent",
        "exclude_docs": exclude,
        "validation": {
            # 文档含大量指向仓库根/eval/tests 的既有相对链接，不属于站点范围，
            # 容忍其缺失而不改写源文档。
            "links": {
                "not_found": "ignore",
                "absolute_links": "ignore",
                "unrecognized_links": "ignore",
            },
            "nav": {"omitted_files": "ignore", "not_found": "ignore"},
        },
        "theme": {
            "name": "material",
            "language": "en",
            "features": [
                "navigation.tabs",
                "navigation.sections",
                "navigation.expand",
                "navigation.top",
                "search.suggest",
                "search.highlight",
                "content.code.copy",
            ],
            "palette": [
                {
                    "media": "(prefers-color-scheme: light)",
                    "scheme": "default",
                    "primary": "indigo",
                    "accent": "indigo",
                    "toggle": {
                        "icon": "material/weather-night",
                        "name": "Switch to dark mode",
                    },
                },
                {
                    "media": "(prefers-color-scheme: dark)",
                    "scheme": "slate",
                    "primary": "indigo",
                    "accent": "indigo",
                    "toggle": {
                        "icon": "material/weather-sunny",
                        "name": "Switch to light mode",
                    },
                },
            ],
        },
        "markdown_extensions": [
            "admonition",
            "pymdownx.details",
            "pymdownx.superfences",
            {"pymdownx.tabbed": {"alternate_style": True}},
            {"toc": {"permalink": True}},
            "attr_list",
            "md_in_html",
            "def_list",
            "footnotes",
            "tables",
        ],
        "plugins": [
            "search",
            {
                "i18n": {
                    "docs_structure": "folder",
                    "reconfigure_material": True,
                    "reconfigure_search": True,
                    "fallback_to_default": True,
                    "languages": [
                        {
                            "locale": "en",
                            "name": "English",
                            "default": True,
                            "build": True,
                        },
                        {
                            "locale": "zh-CN",
                            "name": "简体中文",
                            "build": True,
                            # Material 主题缺少 zh-CN 的语言模板，回退到 zh。
                            "theme": {"language": "zh"},
                        },
                    ],
                }
            },
        ],
        "nav": nav,
    }


def render(config: dict[str, Any]) -> str:
    """把配置字典序列化为带文件头注释的 YAML 文本。"""
    body = yaml.safe_dump(
        config,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=100,
    )
    return f"{HEADER}\n{body}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when mkdocs.yml is missing or stale.",
    )
    args = parser.parse_args()

    expected = render(build_config())

    if args.check:
        if not MKDOCS_PATH.is_file():
            raise SystemExit(
                "mkdocs.yml is missing. Run `python -m scripts.generate_docs_site`."
            )
        if MKDOCS_PATH.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "mkdocs.yml is stale. Run `python -m scripts.generate_docs_site`."
            )
        print("mkdocs.yml is current.")
        return

    MKDOCS_PATH.write_text(expected, encoding="utf-8")
    print(MKDOCS_PATH.relative_to(ROOT))
    ensure_aliases()


if __name__ == "__main__":
    main()
