import argparse
from dataclasses import dataclass
import hashlib
import os
from pathlib import Path
import re
import tempfile


PORT_OFFSETS = {
    "APP_HOST_PORT": 0,
    "POSTGRES_HOST_PORT": 1,
    "REDIS_HOST_PORT": 2,
    "QDRANT_HTTP_PORT": 3,
    "QDRANT_GRPC_PORT": 4,
    "PROMETHEUS_HOST_PORT": 5,
    "GRAFANA_HOST_PORT": 6,
    "E2E_PORT": 7,
}
SAFE_SUFFIX = re.compile(r"^[a-z0-9][a-z0-9-]{0,39}$")


@dataclass(frozen=True)
class WorktreeEnvironment:
    worktree_path: Path
    suffix: str
    project_name: str
    ports: dict[str, int]

    def values(self) -> dict[str, str]:
        return {
            "WORKTREE_SUFFIX": self.suffix,
            "COMPOSE_PROJECT_NAME": self.project_name,
            **{key: str(value) for key, value in self.ports.items()},
        }


def _safe_name(path: Path) -> str:
    value = re.sub(r"[^a-z0-9]+", "-", path.name.lower()).strip("-")
    return (value or "worktree")[:20].rstrip("-")


def generate_environment(
    worktree_path: str | Path,
    *,
    suffix: str | None = None,
) -> WorktreeEnvironment:
    resolved = Path(worktree_path).resolve()
    digest = hashlib.sha256(str(resolved).encode("utf-8")).hexdigest()
    generated_suffix = f"{_safe_name(resolved)}-{digest[:8]}"
    selected_suffix = (suffix or generated_suffix).lower()
    if not SAFE_SUFFIX.fullmatch(selected_suffix):
        raise ValueError(
            "worktree suffix must contain only lowercase letters, digits, "
            "and hyphens (maximum 40 characters)"
        )

    # 2,500 blocks of ten ports span 20000-44999. Eight ports are used,
    # leaving two positions for future local services.
    block_start = 20000 + (int(digest[:8], 16) % 2500) * 10
    ports = {
        key: block_start + offset
        for key, offset in PORT_OFFSETS.items()
    }
    return WorktreeEnvironment(
        worktree_path=resolved,
        suffix=selected_suffix,
        project_name=f"interview-agent-{selected_suffix}",
        ports=ports,
    )


def render_environment(environment: WorktreeEnvironment) -> str:
    values = environment.values()
    lines = [
        "# Generated by python -m scripts.worktree_env; do not commit.",
        f"# Worktree: {environment.worktree_path}",
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())
    return "\n".join(lines) + "\n"


def write_environment(
    environment: WorktreeEnvironment,
    output: str | Path,
) -> Path:
    destination = Path(output)
    if not destination.is_absolute():
        destination = environment.worktree_path / destination
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=destination.parent,
        prefix=f".{destination.name}.",
        delete=False,
    ) as temporary:
        temporary.write(render_environment(environment))
        temporary_path = Path(temporary.name)
    os.replace(temporary_path, destination)
    return destination


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate deterministic per-worktree stack settings."
    )
    parser.add_argument("--root", default=".")
    parser.add_argument("--output", default=".env.worktree")
    parser.add_argument("--suffix")
    parser.add_argument("--print", action="store_true", dest="print_values")
    parser.add_argument(
        "--value",
        choices=("WORKTREE_SUFFIX", "COMPOSE_PROJECT_NAME", *PORT_OFFSETS),
    )
    args = parser.parse_args()

    environment = generate_environment(args.root, suffix=args.suffix)
    if args.value:
        print(environment.values()[args.value])
        return
    if args.print_values:
        print(render_environment(environment), end="")
        return
    destination = write_environment(environment, args.output)
    print(
        f"Generated {destination} for Compose project "
        f"{environment.project_name}"
    )


if __name__ == "__main__":
    main()
